# backend/api/ml_routes.py
#
# API routes for model performance reporting and explainability (XAI).

import json
import os
from fastapi import APIRouter, HTTPException
import numpy as np

router = APIRouter(prefix="/api/ml", tags=["ML & XAI"])


# ── Req #20: Model performance metrics endpoint ──────────────────────────────

@router.get("/metrics")
def get_model_metrics():
    """Return the quality report generated by the most recent training run."""
    report_path = "backend/ml/exports/quality_report.json"
    if not os.path.exists(report_path):
        raise HTTPException(
            status_code=404,
            detail="No quality report found. Train a model first via POST /api/upload/dataset.",
        )
    with open(report_path) as f:
        return json.load(f)


# ── Req #21: SHAP feature importance endpoint ────────────────────────────────

@router.get("/explain/{employee_id}")
def explain_employee_shap(employee_id: int):
    """
    Return SHAP feature importance for a specific employee, bucketed into
    Most / Moderate / Least influential features.
    """
    import joblib
    from sqlmodel import Session, select
    from backend.database import engine as db_engine
    from backend.models import Employee
    from backend.ml.attrition_model import engineer_features

    model_path = "backend/ml/exports/quit_probability.pkl"
    if not os.path.exists(model_path):
        raise HTTPException(status_code=404, detail="No trained model found.")

    saved = joblib.load(model_path)
    base_model = saved["model"]
    features = saved["features"]
    encoders = saved.get("label_encoders", {})

    # If saved model is the raw XGBoost (not calibrated wrapper), use directly
    if hasattr(base_model, "get_booster"):
        xgb_model = base_model
    elif hasattr(base_model, "base_model"):
        xgb_model = base_model
    else:
        xgb_model = base_model

    # Load employee
    with Session(db_engine) as session:
        emp = session.exec(select(Employee).where(Employee.employee_id == employee_id)).first()
    if not emp:
        raise HTTPException(status_code=404, detail=f"Employee {employee_id} not found.")

    import pandas as pd
    raw = {
        "job_satisfaction": emp.job_satisfaction,
        "work_life_balance": emp.work_life_balance,
        "environment_satisfaction": emp.environment_satisfaction,
        "job_involvement": emp.job_involvement,
        "monthly_income": emp.monthly_income,
        "years_at_company": emp.years_at_company,
        "total_working_years": emp.total_working_years,
        "num_companies_worked": emp.num_companies_worked,
        "job_level": emp.job_level,
        "years_since_last_promotion": emp.years_since_last_promotion,
        "years_with_curr_manager": emp.years_with_curr_manager,
        "performance_rating": emp.performance_rating,
        "stock_option_level": emp.stock_option_level,
        "age": emp.age,
        "distance_from_home": emp.distance_from_home,
        "percent_salary_hike": emp.percent_salary_hike,
        "years_in_current_role": getattr(emp, "years_in_current_role", 0) or 0,
        "overtime": getattr(emp, "overtime", 0) or 0,
        "department": emp.department,
        "job_role": emp.job_role,
    }
    df = pd.DataFrame([raw])
    df = engineer_features(df, encoders=encoders)
    X = df[features]

    # Try SHAP — fall back to feature_importances_ if SHAP unavailable
    try:
        import shap
        explainer = shap.TreeExplainer(xgb_model)
        shap_values = explainer.shap_values(X)
        importances = np.abs(shap_values[0])
    except Exception:
        # Fallback: use global feature importances
        importances = xgb_model.feature_importances_

    # Pair feature names with importance values and sort
    pairs = sorted(zip(features, importances.tolist()), key=lambda x: x[1], reverse=True)

    # Bucket into thirds
    n = len(pairs)
    third = max(1, n // 3)
    most = [{"feature": f, "importance": round(v, 4)} for f, v in pairs[:third]]
    moderate = [{"feature": f, "importance": round(v, 4)} for f, v in pairs[third:2*third]]
    least = [{"feature": f, "importance": round(v, 4)} for f, v in pairs[2*third:]]

    return {
        "employee_id": employee_id,
        "method": "shap",
        "buckets": {
            "most_influential": most,
            "moderately_influential": moderate,
            "least_influential": least,
        },
    }


# ── Req #22: LIME stub endpoint ──────────────────────────────────────────────

@router.get("/lime/{employee_id}")
def explain_employee_lime(employee_id: int):
    """Stub endpoint for LIME-based explanations. Not yet implemented."""
    return {
        "employee_id": employee_id,
        "method": "lime",
        "status": "not_implemented",
        "message": "LIME explanations are not yet available. Use /api/ml/explain/{id} for SHAP-based explanations.",
    }
