services:
  db:
    image: postgres:15
    container_name: simuorg_copy_db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simuorg_copy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: simuorg_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/simuorg_copy_db
    depends_on:
      - db

volumes:
  postgres_data: